/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.martinek.ide

import com.google.inject.Guice
import dk.sdu.martinek.MyDSLRuntimeModule
import dk.sdu.martinek.MyDSLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MyDSLIdeSetup extends MyDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MyDSLRuntimeModule, new MyDSLIdeModule))
	}
	
}
