/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.martinek.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class MyDSLWebModule extends AbstractMyDSLWebModule {
}
