/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.martinek


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyDSLStandaloneSetup extends MyDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new MyDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
