/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.martinek


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyDSLRuntimeModule extends AbstractMyDSLRuntimeModule {
}
